version: "3"
services:
  front:
    build:
      context: "./frontend"
      dockerfile: Dockerfile

    ports:
      - 3000:3000

    container_name: react-container
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack-network
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile

    ports:
      - 5000:5000

    container_name: express-container
    networks:
      - mern-stack-network
    volumes:
      - ./backend:/app
    # depends_on:
    #   - mongo
  # mongo:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   container_name: mongo-container
  #   networks:
  #     - mern-stack-network
  #   volumes:
  #     - mongoData: /data/db
  #   env_file:
  #     - ./backend/.env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=dabombs
  #     - MONGO_INITDB_ROOT_PASSWORD=da69
  #     - MONGO_INITDB_DATABASE=audio
networks:
  mern-stack-network:
# volumes:
#   mongoData:
